title: ğ“”ğ“¥ğ“ğ“›ğ“¥ğ“”ğ““
author: Program-evolved
email: frezaxa@gmail.com
description: 
 Programe-Evolved's Fabulous website, this is where i post my greatest evolved immersive programs, also for free  .
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
